/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego_de_memoria.prueba;

import Jugadores.Jugador;
import NivelDificultad.Dificultad;
import cartas.Carta;
import conometros.Conometro;
import controladores.ControladorJuego;
import java.awt.CardLayout;
import javax.swing.JButton;
import tablero.Tablero;


/**
 *
 * @author Nazareth Quirós
 */
public class JfrmJuego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfrmJuego.class.getName());
    private Conometro cronometro = new Conometro();
    private final Jugador jugador = new Jugador();
    private Tablero tablero;
    private ControladorJuego controladorJuego;
    private javax.swing.Timer timerInterfaz;
    private JButton[][] botonesCartas;
    private Dificultad dificultadSeleccionada;
    private javax.swing.JPanel panelActual;
    private int filasActuales;
    private int columnasActuales;
    
    public JfrmJuego() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        comboNivelActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textNivel = new javax.swing.JLabel();
        comboNivel = new javax.swing.JComboBox<>();
        btnReiniciar = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        panelTablero = new javax.swing.JPanel();
        panelPrincipiante = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        panelIntermedio = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        panelAvanzada = new javax.swing.JPanel();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        panelEstadisticas = new javax.swing.JPanel();
        lblPuntajes = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        lblParejas = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();

        lblPuntaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPuntaje.setText("Puntaje");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VentanaJuego");
        setName("Ventana Juego"); // NOI18N

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        textNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nivel.png"))); // NOI18N
        textNivel.setText("Seleccione el Nivel");

        comboNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Avanzada" }));
        comboNivel.addActionListener(this::comboNivelActionPerformed);

        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reload.png"))); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/play.png"))); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 572, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar)
                    .addComponent(textNivel)
                    .addComponent(btnIniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelTablero.setLayout(new java.awt.CardLayout());

        panelPrincipiante.setName("Principiante"); // NOI18N
        panelPrincipiante.setLayout(new java.awt.GridLayout(4, 4));

        jButton1.setText(" ");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        panelPrincipiante.add(jButton1);

        jButton2.setText(" ");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        panelPrincipiante.add(jButton2);

        jButton3.setText(" ");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        panelPrincipiante.add(jButton3);

        jButton4.setText(" ");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        panelPrincipiante.add(jButton4);

        jButton5.setText(" ");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        panelPrincipiante.add(jButton5);

        jButton6.setText(" ");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        panelPrincipiante.add(jButton6);

        jButton7.setText(" ");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        panelPrincipiante.add(jButton7);

        jButton8.setText(" ");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        panelPrincipiante.add(jButton8);

        jButton9.addActionListener(this::jButton9ActionPerformed);
        panelPrincipiante.add(jButton9);

        jButton10.setText(" ");
        jButton10.addActionListener(this::jButton10ActionPerformed);
        panelPrincipiante.add(jButton10);

        jButton11.setText(" ");
        jButton11.addActionListener(this::jButton11ActionPerformed);
        panelPrincipiante.add(jButton11);

        jButton12.setText(" ");
        jButton12.addActionListener(this::jButton12ActionPerformed);
        panelPrincipiante.add(jButton12);

        jButton13.addActionListener(this::jButton13ActionPerformed);
        panelPrincipiante.add(jButton13);

        jButton14.addActionListener(this::jButton14ActionPerformed);
        panelPrincipiante.add(jButton14);

        jButton15.addActionListener(this::jButton15ActionPerformed);
        panelPrincipiante.add(jButton15);

        jButton16.setText(" ");
        jButton16.addActionListener(this::jButton16ActionPerformed);
        panelPrincipiante.add(jButton16);

        panelTablero.add(panelPrincipiante, "panelPrincipiante");

        panelIntermedio.setName("Intermedio"); // NOI18N
        panelIntermedio.setLayout(new java.awt.GridLayout(4, 8));

        jButton17.setText(" ");
        jButton17.addActionListener(this::jButton17ActionPerformed);
        panelIntermedio.add(jButton17);

        jButton18.setText(" ");
        jButton18.addActionListener(this::jButton18ActionPerformed);
        panelIntermedio.add(jButton18);

        jButton19.setText(" ");
        jButton19.addActionListener(this::jButton19ActionPerformed);
        panelIntermedio.add(jButton19);

        jButton20.setText(" ");
        jButton20.addActionListener(this::jButton20ActionPerformed);
        panelIntermedio.add(jButton20);

        jButton21.setText(" ");
        jButton21.addActionListener(this::jButton21ActionPerformed);
        panelIntermedio.add(jButton21);

        jButton22.setText(" ");
        jButton22.addActionListener(this::jButton22ActionPerformed);
        panelIntermedio.add(jButton22);

        jButton23.setText(" ");
        jButton23.addActionListener(this::jButton23ActionPerformed);
        panelIntermedio.add(jButton23);

        jButton24.setText(" ");
        jButton24.addActionListener(this::jButton24ActionPerformed);
        panelIntermedio.add(jButton24);

        jButton25.setText(" ");
        jButton25.addActionListener(this::jButton25ActionPerformed);
        panelIntermedio.add(jButton25);

        jButton26.setText(" ");
        jButton26.addActionListener(this::jButton26ActionPerformed);
        panelIntermedio.add(jButton26);

        jButton27.setText(" ");
        jButton27.addActionListener(this::jButton27ActionPerformed);
        panelIntermedio.add(jButton27);

        jButton28.setText(" ");
        jButton28.addActionListener(this::jButton28ActionPerformed);
        panelIntermedio.add(jButton28);

        jButton29.setText(" ");
        jButton29.addActionListener(this::jButton29ActionPerformed);
        panelIntermedio.add(jButton29);

        jButton30.setText(" ");
        jButton30.addActionListener(this::jButton30ActionPerformed);
        panelIntermedio.add(jButton30);

        jButton31.setText(" ");
        jButton31.addActionListener(this::jButton31ActionPerformed);
        panelIntermedio.add(jButton31);

        jButton32.setText(" ");
        jButton32.addActionListener(this::jButton32ActionPerformed);
        panelIntermedio.add(jButton32);

        jButton33.addActionListener(this::jButton33ActionPerformed);
        panelIntermedio.add(jButton33);

        jButton34.addActionListener(this::jButton34ActionPerformed);
        panelIntermedio.add(jButton34);

        jButton35.addActionListener(this::jButton35ActionPerformed);
        panelIntermedio.add(jButton35);

        jButton36.addActionListener(this::jButton36ActionPerformed);
        panelIntermedio.add(jButton36);

        jButton37.addActionListener(this::jButton37ActionPerformed);
        panelIntermedio.add(jButton37);

        jButton38.addActionListener(this::jButton38ActionPerformed);
        panelIntermedio.add(jButton38);

        jButton39.addActionListener(this::jButton39ActionPerformed);
        panelIntermedio.add(jButton39);

        jButton40.addActionListener(this::jButton40ActionPerformed);
        panelIntermedio.add(jButton40);

        jButton41.setToolTipText("");
        jButton41.addActionListener(this::jButton41ActionPerformed);
        panelIntermedio.add(jButton41);

        jButton42.addActionListener(this::jButton42ActionPerformed);
        panelIntermedio.add(jButton42);

        jButton43.addActionListener(this::jButton43ActionPerformed);
        panelIntermedio.add(jButton43);

        jButton44.addActionListener(this::jButton44ActionPerformed);
        panelIntermedio.add(jButton44);

        jButton45.addActionListener(this::jButton45ActionPerformed);
        panelIntermedio.add(jButton45);

        jButton46.addActionListener(this::jButton46ActionPerformed);
        panelIntermedio.add(jButton46);

        jButton47.addActionListener(this::jButton47ActionPerformed);
        panelIntermedio.add(jButton47);

        jButton48.addActionListener(this::jButton48ActionPerformed);
        panelIntermedio.add(jButton48);

        panelTablero.add(panelIntermedio, "panelIntermedio");

        panelAvanzada.setName("Avanzada"); // NOI18N
        panelAvanzada.setLayout(new java.awt.GridLayout(8, 8));

        jButton49.addActionListener(this::jButton49ActionPerformed);
        panelAvanzada.add(jButton49);

        jButton50.addActionListener(this::jButton50ActionPerformed);
        panelAvanzada.add(jButton50);

        jButton51.addActionListener(this::jButton51ActionPerformed);
        panelAvanzada.add(jButton51);

        jButton52.addActionListener(this::jButton52ActionPerformed);
        panelAvanzada.add(jButton52);

        jButton53.addActionListener(this::jButton53ActionPerformed);
        panelAvanzada.add(jButton53);

        jButton54.setToolTipText("");
        jButton54.addActionListener(this::jButton54ActionPerformed);
        panelAvanzada.add(jButton54);

        jButton55.addActionListener(this::jButton55ActionPerformed);
        panelAvanzada.add(jButton55);

        jButton56.addActionListener(this::jButton56ActionPerformed);
        panelAvanzada.add(jButton56);

        jButton57.addActionListener(this::jButton57ActionPerformed);
        panelAvanzada.add(jButton57);

        jButton58.addActionListener(this::jButton58ActionPerformed);
        panelAvanzada.add(jButton58);

        jButton59.addActionListener(this::jButton59ActionPerformed);
        panelAvanzada.add(jButton59);

        jButton60.addActionListener(this::jButton60ActionPerformed);
        panelAvanzada.add(jButton60);

        jButton61.addActionListener(this::jButton61ActionPerformed);
        panelAvanzada.add(jButton61);

        jButton62.addActionListener(this::jButton62ActionPerformed);
        panelAvanzada.add(jButton62);

        jButton63.addActionListener(this::jButton63ActionPerformed);
        panelAvanzada.add(jButton63);

        jButton64.addActionListener(this::jButton64ActionPerformed);
        panelAvanzada.add(jButton64);

        jButton65.addActionListener(this::jButton65ActionPerformed);
        panelAvanzada.add(jButton65);

        jButton66.addActionListener(this::jButton66ActionPerformed);
        panelAvanzada.add(jButton66);

        jButton67.addActionListener(this::jButton67ActionPerformed);
        panelAvanzada.add(jButton67);

        jButton68.addActionListener(this::jButton68ActionPerformed);
        panelAvanzada.add(jButton68);

        jButton69.setToolTipText("");
        jButton69.addActionListener(this::jButton69ActionPerformed);
        panelAvanzada.add(jButton69);

        jButton70.addActionListener(this::jButton70ActionPerformed);
        panelAvanzada.add(jButton70);

        jButton71.addActionListener(this::jButton71ActionPerformed);
        panelAvanzada.add(jButton71);

        jButton72.addActionListener(this::jButton72ActionPerformed);
        panelAvanzada.add(jButton72);

        jButton73.setToolTipText("");
        jButton73.addActionListener(this::jButton73ActionPerformed);
        panelAvanzada.add(jButton73);

        jButton74.addActionListener(this::jButton74ActionPerformed);
        panelAvanzada.add(jButton74);

        jButton75.addActionListener(this::jButton75ActionPerformed);
        panelAvanzada.add(jButton75);

        jButton76.addActionListener(this::jButton76ActionPerformed);
        panelAvanzada.add(jButton76);

        jButton77.addActionListener(this::jButton77ActionPerformed);
        panelAvanzada.add(jButton77);

        jButton78.addActionListener(this::jButton78ActionPerformed);
        panelAvanzada.add(jButton78);

        jButton79.addActionListener(this::jButton79ActionPerformed);
        panelAvanzada.add(jButton79);

        jButton80.addActionListener(this::jButton80ActionPerformed);
        panelAvanzada.add(jButton80);

        jButton81.addActionListener(this::jButton81ActionPerformed);
        panelAvanzada.add(jButton81);

        jButton82.addActionListener(this::jButton82ActionPerformed);
        panelAvanzada.add(jButton82);

        jButton83.addActionListener(this::jButton83ActionPerformed);
        panelAvanzada.add(jButton83);

        jButton84.addActionListener(this::jButton84ActionPerformed);
        panelAvanzada.add(jButton84);

        jButton85.addActionListener(this::jButton85ActionPerformed);
        panelAvanzada.add(jButton85);

        jButton86.addActionListener(this::jButton86ActionPerformed);
        panelAvanzada.add(jButton86);

        jButton87.addActionListener(this::jButton87ActionPerformed);
        panelAvanzada.add(jButton87);

        jButton88.addActionListener(this::jButton88ActionPerformed);
        panelAvanzada.add(jButton88);

        jButton89.addActionListener(this::jButton89ActionPerformed);
        panelAvanzada.add(jButton89);

        jButton90.addActionListener(this::jButton90ActionPerformed);
        panelAvanzada.add(jButton90);

        jButton91.addActionListener(this::jButton91ActionPerformed);
        panelAvanzada.add(jButton91);

        jButton92.addActionListener(this::jButton92ActionPerformed);
        panelAvanzada.add(jButton92);

        jButton93.addActionListener(this::jButton93ActionPerformed);
        panelAvanzada.add(jButton93);

        jButton94.addActionListener(this::jButton94ActionPerformed);
        panelAvanzada.add(jButton94);

        jButton95.addActionListener(this::jButton95ActionPerformed);
        panelAvanzada.add(jButton95);

        jButton96.addActionListener(this::jButton96ActionPerformed);
        panelAvanzada.add(jButton96);

        jButton97.addActionListener(this::jButton97ActionPerformed);
        panelAvanzada.add(jButton97);

        jButton98.addActionListener(this::jButton98ActionPerformed);
        panelAvanzada.add(jButton98);

        jButton99.addActionListener(this::jButton99ActionPerformed);
        panelAvanzada.add(jButton99);

        jButton100.addActionListener(this::jButton100ActionPerformed);
        panelAvanzada.add(jButton100);

        jButton101.addActionListener(this::jButton101ActionPerformed);
        panelAvanzada.add(jButton101);

        jButton102.addActionListener(this::jButton102ActionPerformed);
        panelAvanzada.add(jButton102);

        jButton103.addActionListener(this::jButton103ActionPerformed);
        panelAvanzada.add(jButton103);

        jButton104.setToolTipText("");
        jButton104.addActionListener(this::jButton104ActionPerformed);
        panelAvanzada.add(jButton104);

        jButton105.addActionListener(this::jButton105ActionPerformed);
        panelAvanzada.add(jButton105);

        jButton106.addActionListener(this::jButton106ActionPerformed);
        panelAvanzada.add(jButton106);

        jButton107.addActionListener(this::jButton107ActionPerformed);
        panelAvanzada.add(jButton107);

        jButton108.addActionListener(this::jButton108ActionPerformed);
        panelAvanzada.add(jButton108);

        jButton109.addActionListener(this::jButton109ActionPerformed);
        panelAvanzada.add(jButton109);

        jButton110.addActionListener(this::jButton110ActionPerformed);
        panelAvanzada.add(jButton110);

        jButton111.addActionListener(this::jButton111ActionPerformed);
        panelAvanzada.add(jButton111);

        jButton112.addActionListener(this::jButton112ActionPerformed);
        panelAvanzada.add(jButton112);

        panelTablero.add(panelAvanzada, "panelAvanzada");
        panelAvanzada.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(panelTablero, java.awt.BorderLayout.CENTER);

        panelEstadisticas.setLayout(new java.awt.GridLayout(1, 4));

        lblPuntajes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPuntajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/star.png"))); // NOI18N
        lblPuntajes.setText("Puntaje");
        panelEstadisticas.add(lblPuntajes);

        lblIntentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/target.png"))); // NOI18N
        lblIntentos.setText("Intentos");
        panelEstadisticas.add(lblIntentos);

        lblParejas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblParejas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/playing-cards.png"))); // NOI18N
        lblParejas.setText("Parejas encontradas");
        panelEstadisticas.add(lblParejas);

        lblTiempo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hourglass.png"))); // NOI18N
        lblTiempo.setText("Tiempo");
        panelEstadisticas.add(lblTiempo);

        getContentPane().add(panelEstadisticas, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
       procesarClicBoton(evt);
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
       procesarClicBoton(evt);
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
       procesarClicBoton(evt);
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
       procesarClicBoton(evt);
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
       procesarClicBoton(evt);
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
       procesarClicBoton(evt);
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton68ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton68ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
       procesarClicBoton(evt);
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton70ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton72ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton74ActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton75ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton76ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton77ActionPerformed

    private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton78ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton78ActionPerformed

    private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton79ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton79ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton80ActionPerformed

    private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton81ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton81ActionPerformed

    private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton82ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton82ActionPerformed

    private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton83ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton83ActionPerformed

    private void jButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton84ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton84ActionPerformed

    private void jButton85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton85ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton85ActionPerformed

    private void jButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton86ActionPerformed
       procesarClicBoton(evt);
    }//GEN-LAST:event_jButton86ActionPerformed

    private void jButton87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton87ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton87ActionPerformed

    private void jButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton88ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton88ActionPerformed

    private void jButton89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton89ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton89ActionPerformed

    private void jButton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton90ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton90ActionPerformed

    private void jButton91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton91ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton91ActionPerformed

    private void jButton92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton92ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton92ActionPerformed

    private void jButton93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton93ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton93ActionPerformed

    private void jButton94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton94ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton94ActionPerformed

    private void jButton95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton95ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton95ActionPerformed

    private void jButton96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton96ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton96ActionPerformed

    private void jButton97ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton97ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton97ActionPerformed

    private void jButton98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton98ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton98ActionPerformed

    private void jButton99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton99ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton99ActionPerformed

    private void jButton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton100ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton100ActionPerformed

    private void jButton101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton101ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton101ActionPerformed

    private void jButton102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton102ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton102ActionPerformed

    private void jButton103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton103ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton103ActionPerformed

    private void jButton104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton104ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton104ActionPerformed

    private void jButton105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton105ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton105ActionPerformed

    private void jButton106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton106ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton106ActionPerformed

    private void jButton107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton107ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton107ActionPerformed

    private void jButton108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton108ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton108ActionPerformed

    private void jButton109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton109ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton109ActionPerformed

    private void jButton110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton110ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton110ActionPerformed

    private void jButton111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton111ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton111ActionPerformed

    private void jButton112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton112ActionPerformed
        procesarClicBoton(evt);
    }//GEN-LAST:event_jButton112ActionPerformed

    private void comboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNivelActionPerformed
        String nivelSeleccionado = (String) comboNivel.getSelectedItem();
        CardLayout cl = (CardLayout) panelTablero.getLayout();
        if (nivelSeleccionado.equals("Principiante")) {
            cl.show(panelTablero, "panelPrincipiante");
            dificultadSeleccionada = Dificultad.PRINCIPIANTE;
            panelActual = panelPrincipiante;
            filasActuales = 4;
            columnasActuales = 4;
        } else if (nivelSeleccionado.equals("Intermedio")) {
            cl.show(panelTablero, "panelIntermedio");
            dificultadSeleccionada = Dificultad.INTERMEDIO;
            panelActual = panelIntermedio;
            filasActuales = 4;
            columnasActuales = 8;
        } else if (nivelSeleccionado.equals("Avanzada")) {
            cl.show(panelTablero, "panelAvanzada");
            dificultadSeleccionada = Dificultad.AVANZADA;
            panelActual = panelAvanzada;
            filasActuales = 8;
            columnasActuales = 8;
        }
    }//GEN-LAST:event_comboNivelActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        comboNivel.setEnabled(false);
        btnIniciar.setEnabled(false);
        
        tablero = new Tablero(dificultadSeleccionada);
        tablero.setListaUsada(new String[]{});
        controladorJuego = new ControladorJuego(cronometro, jugador, tablero, null, null);
        controladorJuego.iniciarJuego();
        
        botonesCartas = obtenerBotonesPanel(panelActual,filasActuales,columnasActuales);
       
        if(timerInterfaz != null){
            timerInterfaz.stop();
        }
        timerInterfaz = new javax.swing.Timer(1000, e ->{
        lblTiempo.setText(String.format("Tiempo: %02d:%02d", cronometro.getMinutos(),cronometro.getSegundos()));
        });
        timerInterfaz.start();
        
        actualizarInterfaz();
        
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        if(timerInterfaz != null){
            timerInterfaz.stop();
        }
        cronometro.reiniciar();
        jugador.reiniciar();
        lblTiempo.setText("Tiempo: 00:00");
        lblIntentos.setText("Intentos: 0");
        comboNivel.setEnabled(true);
        btnIniciar.setEnabled(true);
        java.awt.CardLayout cl = (java.awt.CardLayout) panelTablero.getLayout();
    }//GEN-LAST:event_btnReiniciarActionPerformed
    
    private void procesarClicBoton(java.awt.event.ActionEvent evt){
        if(botonesCartas == null){
            return;
        }
        JButton botonSeleccionado = (JButton) evt.getSource();
        for(int i = 0; i < botonesCartas.length; i++){
            for(int j = 0; j < botonesCartas[i].length; j++){
                if(botonesCartas[i][j] == botonSeleccionado){
                    manejarClicCarta(i, j);
                    return;
                }
            }
        }
    }
    private JButton[][] obtenerBotonesPanel(javax.swing.JPanel panel,int filas, int columnas){
        JButton[][] botones = new JButton[filas][columnas];
        java.awt.Component[] componentes = panel.getComponents();
        int indi = 0;
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                JButton boton = (JButton) componentes[indi];
                botones[i][j] = boton;
                boton.setIcon(null);
                indi++;
            }
        }
        return botones;
    }
    private void manejarClicCarta(int fila, int columna){
        controladorJuego.seleccionarCarta(fila, columna);
        actualizarInterfaz();
        if(tablero.validarTodaslasCartas()){
           // mostrarResultado();
        }
    }
    
    private void actualizarInterfaz(){
        lblPuntajes.setText("Puntaje: " + jugador.getPuntaje());
        lblIntentos.setText("Intentos: " + jugador.getIntentos());
        lblParejas.setText("Parejas Encontadas: " + jugador.getParejas());
        
        Carta[][] cartas = tablero.getCartas();
        for (int i = 0; i < cartas.length; i++) {
            for (int j = 0; j < cartas[i].length; j++) {
                Carta carta = cartas[i][j];
                if(carta.isEstado()){
                    String numeroImagen = carta.getImagen().replace("carta_","");
                    botonesCartas[i][j].setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/Imagenes/" + numeroImagen + ".png")));
                }else{
                    botonesCartas[i][j].setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/iconos/signo-de-pregunta.png")));;
                }
            }    
        }
    }
    
    private void mostrarResultado(){
        timerInterfaz.stop();
        cronometro.detener();
        
        JfrmResultado resultado = new JfrmResultado();
        
        resultado.lblPuntajeFinal.setText(String.valueOf(jugador.getPuntaje()));
        resultado.lblIntentosFinal.setText(String.valueOf(jugador.getIntentos()));
        resultado.lblTiempoFinal.setText(String.format("%02d:%02d", cronometro.getMinutos(), cronometro.getSegundos()));
       resultado.lblNivelFinal.setText(String.valueOf(jugador.getPuntaje()));
       resultado.setVisible(true);
       this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfrmJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblParejas;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblPuntajes;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JPanel panelAvanzada;
    private javax.swing.JPanel panelEstadisticas;
    private javax.swing.JPanel panelIntermedio;
    private javax.swing.JPanel panelPrincipiante;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JLabel textNivel;
    // End of variables declaration//GEN-END:variables
}
