/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego_de_memoria.prueba;

public class JfrmResultado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfrmResultado.class.getName());

    /**
     * Creates new form JfrmResultado
     */
    public JfrmResultado() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panelResultado = new javax.swing.JPanel();
        lblPuntaje = new javax.swing.JLabel();
        lblPuntajeFinal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIntentosFinal = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblTiempoFinal = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblNivelFinal = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnJugarDeNuevo = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 244));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("¡Felicidades!");
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        panelResultado.setName("panelResultado"); // NOI18N
        panelResultado.setLayout(new java.awt.GridLayout(4, 4));

        lblPuntaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPuntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/star.png"))); // NOI18N
        lblPuntaje.setText("Puntaje Final");
        panelResultado.add(lblPuntaje);

        lblPuntajeFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.add(lblPuntajeFinal);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/target.png"))); // NOI18N
        jLabel3.setText("Intentos");
        panelResultado.add(jLabel3);

        lblIntentosFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.add(lblIntentosFinal);

        lblTiempo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hourglass.png"))); // NOI18N
        lblTiempo.setText("Tiempo");
        panelResultado.add(lblTiempo);

        lblTiempoFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.add(lblTiempoFinal);

        lblNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nivel.png"))); // NOI18N
        lblNivel.setText("Nivel");
        panelResultado.add(lblNivel);

        lblNivelFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.add(lblNivelFinal);

        getContentPane().add(panelResultado, java.awt.BorderLayout.CENTER);

        panelBotones.setName("panelBotones"); // NOI18N

        btnJugarDeNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJugarDeNuevo.setText("Jugar de Nuevo");
        btnJugarDeNuevo.addActionListener(this::btnJugarDeNuevoActionPerformed);
        panelBotones.add(btnJugarDeNuevo);

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        panelBotones.add(btnCerrar);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarDeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarDeNuevoActionPerformed
        // TODO add your handling code here:
        JfrmJuego ventana = new JfrmJuego();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJugarDeNuevoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfrmResultado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnJugarDeNuevo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblIntentosFinal;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNivelFinal;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblPuntajeFinal;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTiempoFinal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelResultado;
    // End of variables declaration//GEN-END:variables
}
