/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego_de_memoria.prueba;

import java.awt.CardLayout;

/**
 *
 * @author Nazareth Quirós
 */
public class JfrmJuego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfrmJuego.class.getName());

    /**
     * Creates new form JfrmJuego
     */
    public JfrmJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textNivel = new javax.swing.JLabel();
        ComboNivel = new javax.swing.JComboBox<>();
        btnReiniciar = new javax.swing.JButton();
        panelTablero = new javax.swing.JPanel();
        panelPrincipiante = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        panelIntermedio = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        panelAvanzado = new javax.swing.JPanel();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        panelEstadisticas = new javax.swing.JPanel();
        lblPuntajes = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        lblParejas = new javax.swing.JLabel();
        lblTiempos = new javax.swing.JLabel();

        lblPuntaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPuntaje.setText("Puntaje");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VentanaJuego");
        setName("Ventana Juego"); // NOI18N

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        textNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textNivel.setText("Nivel");

        ComboNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ComboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Avanzado" }));
        ComboNivel.addActionListener(this::ComboNivelActionPerformed);

        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReiniciar.setText("Reiniciar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(ComboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 720, Short.MAX_VALUE)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar)
                    .addComponent(textNivel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelTablero.setLayout(new java.awt.CardLayout());

        panelPrincipiante.setName("Principiante"); // NOI18N
        panelPrincipiante.setLayout(new java.awt.GridLayout(4, 4));

        jButton1.setText("jButton1");
        panelPrincipiante.add(jButton1);

        jButton2.setText("jButton1");
        panelPrincipiante.add(jButton2);

        jButton3.setText("jButton1");
        panelPrincipiante.add(jButton3);

        jButton4.setText("jButton1");
        panelPrincipiante.add(jButton4);

        jButton5.setText("jButton1");
        panelPrincipiante.add(jButton5);

        jButton6.setText("jButton1");
        panelPrincipiante.add(jButton6);

        jButton7.setText("jButton1");
        panelPrincipiante.add(jButton7);

        jButton8.setText("jButton1");
        panelPrincipiante.add(jButton8);

        jButton9.setText("jButton1");
        panelPrincipiante.add(jButton9);

        jButton10.setText("jButton1");
        panelPrincipiante.add(jButton10);

        jButton11.setText("jButton1");
        panelPrincipiante.add(jButton11);

        jButton12.setText("jButton1");
        panelPrincipiante.add(jButton12);

        jButton13.setText("jButton1");
        panelPrincipiante.add(jButton13);

        jButton14.setText("jButton1");
        panelPrincipiante.add(jButton14);

        jButton15.setText("jButton1");
        panelPrincipiante.add(jButton15);

        jButton16.setText("jButton1");
        panelPrincipiante.add(jButton16);

        panelTablero.add(panelPrincipiante, "panelPrincipiante");

        panelIntermedio.setName("Intermedio"); // NOI18N
        panelIntermedio.setLayout(new java.awt.GridLayout(8, 4));

        jButton17.setText("jButton1");
        panelIntermedio.add(jButton17);

        jButton18.setText("jButton1");
        panelIntermedio.add(jButton18);

        jButton19.setText("jButton1");
        panelIntermedio.add(jButton19);

        jButton20.setText("jButton1");
        panelIntermedio.add(jButton20);

        jButton21.setText("jButton1");
        panelIntermedio.add(jButton21);

        jButton22.setText("jButton1");
        panelIntermedio.add(jButton22);

        jButton23.setText("jButton1");
        panelIntermedio.add(jButton23);

        jButton24.setText("jButton1");
        panelIntermedio.add(jButton24);

        jButton25.setText("jButton1");
        panelIntermedio.add(jButton25);

        jButton26.setText("jButton1");
        panelIntermedio.add(jButton26);

        jButton27.setText("jButton1");
        panelIntermedio.add(jButton27);

        jButton28.setText("jButton1");
        panelIntermedio.add(jButton28);

        jButton29.setText("jButton1");
        panelIntermedio.add(jButton29);

        jButton30.setText("jButton1");
        panelIntermedio.add(jButton30);

        jButton31.setText("jButton1");
        panelIntermedio.add(jButton31);

        jButton32.setText("jButton1");
        panelIntermedio.add(jButton32);

        jButton33.setText("jButton1");
        panelIntermedio.add(jButton33);

        jButton34.setText("jButton1");
        panelIntermedio.add(jButton34);

        jButton35.setText("jButton1");
        panelIntermedio.add(jButton35);

        jButton36.setText("jButton1");
        panelIntermedio.add(jButton36);

        jButton37.setText("jButton1");
        panelIntermedio.add(jButton37);

        jButton38.setText("jButton1");
        panelIntermedio.add(jButton38);

        jButton39.setText("jButton1");
        panelIntermedio.add(jButton39);

        jButton40.setText("jButton1");
        panelIntermedio.add(jButton40);

        jButton41.setText("jButton1");
        panelIntermedio.add(jButton41);

        jButton42.setText("jButton1");
        panelIntermedio.add(jButton42);

        jButton43.setText("jButton1");
        panelIntermedio.add(jButton43);

        jButton44.setText("jButton1");
        panelIntermedio.add(jButton44);

        jButton45.setText("jButton1");
        panelIntermedio.add(jButton45);

        jButton46.setText("jButton1");
        panelIntermedio.add(jButton46);

        jButton47.setText("jButton1");
        panelIntermedio.add(jButton47);

        jButton48.setText("jButton1");
        panelIntermedio.add(jButton48);

        panelTablero.add(panelIntermedio, "panelIntermedio");

        panelAvanzado.setName("Avanzado"); // NOI18N
        panelAvanzado.setLayout(new java.awt.GridLayout(8, 8));

        jButton49.setText("jButton1");
        panelAvanzado.add(jButton49);

        jButton50.setText("jButton1");
        panelAvanzado.add(jButton50);

        jButton51.setText("jButton1");
        panelAvanzado.add(jButton51);

        jButton52.setText("jButton1");
        panelAvanzado.add(jButton52);

        jButton53.setText("jButton1");
        panelAvanzado.add(jButton53);

        jButton54.setText("jButton1");
        panelAvanzado.add(jButton54);

        jButton55.setText("jButton1");
        panelAvanzado.add(jButton55);

        jButton56.setText("jButton1");
        panelAvanzado.add(jButton56);

        jButton57.setText("jButton1");
        panelAvanzado.add(jButton57);

        jButton58.setText("jButton1");
        panelAvanzado.add(jButton58);

        jButton59.setText("jButton1");
        panelAvanzado.add(jButton59);

        jButton60.setText("jButton1");
        panelAvanzado.add(jButton60);

        jButton61.setText("jButton1");
        panelAvanzado.add(jButton61);

        jButton62.setText("jButton1");
        panelAvanzado.add(jButton62);

        jButton63.setText("jButton1");
        panelAvanzado.add(jButton63);

        jButton64.setText("jButton1");
        panelAvanzado.add(jButton64);

        jButton65.setText("jButton1");
        panelAvanzado.add(jButton65);

        jButton66.setText("jButton1");
        panelAvanzado.add(jButton66);

        jButton67.setText("jButton1");
        panelAvanzado.add(jButton67);

        jButton68.setText("jButton1");
        panelAvanzado.add(jButton68);

        jButton69.setText("jButton1");
        panelAvanzado.add(jButton69);

        jButton70.setText("jButton1");
        panelAvanzado.add(jButton70);

        jButton71.setText("jButton1");
        panelAvanzado.add(jButton71);

        jButton72.setText("jButton1");
        panelAvanzado.add(jButton72);

        jButton73.setText("jButton1");
        panelAvanzado.add(jButton73);

        jButton74.setText("jButton1");
        panelAvanzado.add(jButton74);

        jButton75.setText("jButton1");
        panelAvanzado.add(jButton75);

        jButton76.setText("jButton1");
        panelAvanzado.add(jButton76);

        jButton77.setText("jButton1");
        panelAvanzado.add(jButton77);

        jButton78.setText("jButton1");
        panelAvanzado.add(jButton78);

        jButton79.setText("jButton1");
        panelAvanzado.add(jButton79);

        jButton80.setText("jButton1");
        panelAvanzado.add(jButton80);

        jButton81.setText("jButton1");
        panelAvanzado.add(jButton81);

        jButton82.setText("jButton1");
        panelAvanzado.add(jButton82);

        jButton83.setText("jButton1");
        panelAvanzado.add(jButton83);

        jButton84.setText("jButton1");
        panelAvanzado.add(jButton84);

        jButton85.setText("jButton1");
        panelAvanzado.add(jButton85);

        jButton86.setText("jButton1");
        panelAvanzado.add(jButton86);

        jButton87.setText("jButton1");
        panelAvanzado.add(jButton87);

        jButton88.setText("jButton1");
        panelAvanzado.add(jButton88);

        jButton89.setText("jButton1");
        panelAvanzado.add(jButton89);

        jButton90.setText("jButton1");
        panelAvanzado.add(jButton90);

        jButton91.setText("jButton1");
        panelAvanzado.add(jButton91);

        jButton92.setText("jButton1");
        panelAvanzado.add(jButton92);

        jButton93.setText("jButton1");
        panelAvanzado.add(jButton93);

        jButton94.setText("jButton1");
        panelAvanzado.add(jButton94);

        jButton95.setText("jButton1");
        panelAvanzado.add(jButton95);

        jButton96.setText("jButton1");
        panelAvanzado.add(jButton96);

        jButton97.setText("jButton1");
        panelAvanzado.add(jButton97);

        jButton98.setText("jButton1");
        panelAvanzado.add(jButton98);

        jButton99.setText("jButton1");
        panelAvanzado.add(jButton99);

        jButton100.setText("jButton1");
        panelAvanzado.add(jButton100);

        jButton101.setText("jButton1");
        panelAvanzado.add(jButton101);

        jButton102.setText("jButton1");
        panelAvanzado.add(jButton102);

        jButton103.setText("jButton1");
        panelAvanzado.add(jButton103);

        jButton104.setText("jButton1");
        panelAvanzado.add(jButton104);

        jButton105.setText("jButton1");
        panelAvanzado.add(jButton105);

        jButton106.setText("jButton1");
        panelAvanzado.add(jButton106);

        jButton107.setText("jButton1");
        panelAvanzado.add(jButton107);

        jButton108.setText("jButton1");
        panelAvanzado.add(jButton108);

        jButton109.setText("jButton1");
        panelAvanzado.add(jButton109);

        jButton110.setText("jButton1");
        panelAvanzado.add(jButton110);

        jButton111.setText("jButton1");
        panelAvanzado.add(jButton111);

        jButton112.setText("jButton1");
        panelAvanzado.add(jButton112);

        panelTablero.add(panelAvanzado, "panelAvanzado");
        panelAvanzado.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(panelTablero, java.awt.BorderLayout.CENTER);

        panelEstadisticas.setLayout(new java.awt.GridLayout(1, 4));

        lblPuntajes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPuntajes.setText("Puntaje");
        panelEstadisticas.add(lblPuntajes);

        lblIntentos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntentos.setText("Intentos");
        panelEstadisticas.add(lblIntentos);

        lblParejas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblParejas.setText("Parejas");
        panelEstadisticas.add(lblParejas);

        lblTiempos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTiempos.setText("Tiempo");
        panelEstadisticas.add(lblTiempos);

        getContentPane().add(panelEstadisticas, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNivelActionPerformed
        String nivelSeleccionado = (String) ComboNivel.getSelectedItem();
        CardLayout cl = (CardLayout) panelTablero.getLayout();

        if (nivelSeleccionado.equals("Principiante")) {
            cl.show(panelTablero, "panelPrincipiante");
        } else if (nivelSeleccionado.equals("Intermedio")) {
            cl.show(panelTablero, "panelIntermedio");
        } else if (nivelSeleccionado.equals("Avanzado")) {
            cl.show(panelTablero, "panelAvanzado");
        }
    }//GEN-LAST:event_ComboNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfrmJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboNivel;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblParejas;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblPuntajes;
    private javax.swing.JLabel lblTiempos;
    private javax.swing.JPanel panelAvanzado;
    private javax.swing.JPanel panelEstadisticas;
    private javax.swing.JPanel panelIntermedio;
    private javax.swing.JPanel panelPrincipiante;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JLabel textNivel;
    // End of variables declaration//GEN-END:variables
}
