/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego_de_memoria.prueba;

public class JfrmResultado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfrmResultado.class.getName());

    /**
     * Creates new form JfrmResultado
     */
    public JfrmResultado() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panelResultado = new javax.swing.JPanel();
        lblNivel = new javax.swing.JLabel();
        lblNiveles = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();
        lblPuntajeFinal = new javax.swing.JLabel();
        lblIntento = new javax.swing.JLabel();
        lblIntentosFinal = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblTiempoFinal = new javax.swing.JLabel();
        lblPareja = new javax.swing.JLabel();
        lblParejaEncontradas = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnJugarDeNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("¡Felicidades!");
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        panelResultado.setName("panelResultado"); // NOI18N
        panelResultado.setLayout(new java.awt.GridLayout(5, 4));

        lblNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nivel.png"))); // NOI18N
        lblNivel.setText("Nivel");
        panelResultado.add(lblNivel);

        lblNiveles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.add(lblNiveles);

        lblPuntaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPuntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/star.png"))); // NOI18N
        lblPuntaje.setText("Puntaje Final");
        panelResultado.add(lblPuntaje);

        lblPuntajeFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPuntajeFinal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelResultado.add(lblPuntajeFinal);

        lblIntento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIntento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/target.png"))); // NOI18N
        lblIntento.setText("Intentos");
        panelResultado.add(lblIntento);

        lblIntentosFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.add(lblIntentosFinal);

        lblTiempo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/hourglass.png"))); // NOI18N
        lblTiempo.setText("Tiempo");
        panelResultado.add(lblTiempo);

        lblTiempoFinal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.add(lblTiempoFinal);

        lblPareja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPareja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/playing-cards.png"))); // NOI18N
        lblPareja.setText("Parejas Encontradas");
        panelResultado.add(lblPareja);

        lblParejaEncontradas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelResultado.add(lblParejaEncontradas);

        getContentPane().add(panelResultado, java.awt.BorderLayout.CENTER);

        panelBotones.setName("panelBotones"); // NOI18N

        btnJugarDeNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJugarDeNuevo.setText("Jugar de Nuevo");
        btnJugarDeNuevo.addActionListener(this::btnJugarDeNuevoActionPerformed);
        panelBotones.add(btnJugarDeNuevo);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        panelBotones.add(btnSalir);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarDeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarDeNuevoActionPerformed
        // TODO add your handling code here:
        JfrmJuego ventana = new JfrmJuego();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJugarDeNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfrmResultado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugarDeNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblIntento;
    public javax.swing.JLabel lblIntentosFinal;
    private javax.swing.JLabel lblNivel;
    public javax.swing.JLabel lblNiveles;
    private javax.swing.JLabel lblPareja;
    public javax.swing.JLabel lblParejaEncontradas;
    private javax.swing.JLabel lblPuntaje;
    public javax.swing.JLabel lblPuntajeFinal;
    private javax.swing.JLabel lblTiempo;
    public javax.swing.JLabel lblTiempoFinal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelResultado;
    // End of variables declaration//GEN-END:variables
}
